#!/usr/bin/env bash
# Entrypoint for the Factorio headless server container.
#
# Responsibilities:
#   * make /factorio usable no matter how it was mounted (named volume, bind
#     mount, empty directory) and hand it to the unprivileged factorio user;
#   * seed the volume with the example configuration shipped in the release;
#   * create a map the first time the server is started;
#   * exec the server so it receives SIGTERM directly and can save + quit.
set -euo pipefail

FACTORIO_DIR=/opt/factorio
DATA_DIR="${FACTORIO_HOME:-/factorio}"
BINARY="${FACTORIO_DIR}/bin/x64/factorio"

log() { printf '[entrypoint] %s\n' "$*"; }
die() { printf '[entrypoint] ERROR: %s\n' "$*" >&2; exit 1; }

is_true() {
    case "${1,,}" in
        1 | true | yes | on) return 0 ;;
        *) return 1 ;;
    esac
}

# --- escape hatches -------------------------------------------------------
# `docker run <image> bash` and friends still work.
if [[ $# -gt 0 ]]; then
    case "$1" in
        bash | sh | /bin/bash | /bin/sh)
            exec "$@"
            ;;
        --version | --help)
            exec "${BINARY}" "$@"
            ;;
    esac
fi

# --- privilege handling ---------------------------------------------------
if [[ "$(id -u)" -eq 0 ]]; then
    puid="${PUID:-845}"
    pgid="${PGID:-845}"

    if [[ "$(id -g factorio)" != "${pgid}" ]]; then
        groupmod -o -g "${pgid}" factorio
    fi
    if [[ "$(id -u factorio)" != "${puid}" ]]; then
        usermod -o -u "${puid}" factorio
    fi

    mkdir -p "${DATA_DIR}"/{config,saves,mods,scenarios,script-output}
    # Only chown when needed: a large saves directory makes an unconditional
    # recursive chown noticeably slow on every start.
    if [[ "$(stat -c '%u' "${DATA_DIR}")" != "${puid}" ]]; then
        log "Fixing ownership of ${DATA_DIR} (${puid}:${pgid})"
        chown -R "${puid}:${pgid}" "${DATA_DIR}"
    else
        chown "${puid}:${pgid}" "${DATA_DIR}"/{config,saves,mods,scenarios,script-output} 2>/dev/null || true
    fi

    log "Dropping privileges to ${puid}:${pgid}"
    exec gosu "${puid}:${pgid}" "$0" "$@"
fi

# --- from here on we are the unprivileged user ----------------------------
mkdir -p "${DATA_DIR}"/{config,saves,mods,scenarios,script-output}

CONFIG_FILE="${DATA_DIR}/config/config.ini"
SERVER_SETTINGS="${DATA_DIR}/config/server-settings.json"
MAP_GEN_SETTINGS="${DATA_DIR}/config/map-gen-settings.json"
MAP_SETTINGS="${DATA_DIR}/config/map-settings.json"
SERVER_WHITELIST="${DATA_DIR}/config/server-whitelist.json"

seed_config() {
    local target="$1" source="$2"
    if [[ ! -f "${target}" && -f "${source}" ]]; then
        log "Seeding $(basename "${target}") from the shipped example"
        cp "${source}" "${target}"
    fi
}

seed_config "${SERVER_SETTINGS}" "${FACTORIO_DIR}/doc/server-settings.example.json"
seed_config "${MAP_GEN_SETTINGS}" "${FACTORIO_DIR}/doc/map-gen-settings.example.json"
seed_config "${MAP_SETTINGS}" "${FACTORIO_DIR}/doc/map-settings.example.json"
# server-whitelist.json is deliberately NOT seeded: the shipped example lists
# two Wube developers, so seeding it would switch on a whitelist that locks
# every other player out. Create the file yourself to enable the whitelist.

# Point Factorio's read/write data directories at the volume so saves, mods,
# logs and script output all survive a container replacement.
if [[ ! -f "${CONFIG_FILE}" ]]; then
    log "Writing ${CONFIG_FILE}"
    cat > "${CONFIG_FILE}" <<EOF
; Generated by the container entrypoint. Edit freely - it is never rewritten.
[path]
read-data=${FACTORIO_DIR}/data
write-data=${DATA_DIR}

[general]

[other]
check-updates=false
enable-crash-log-uploading=false
EOF
fi

# --- RCON password --------------------------------------------------------
RCON_PW_FILE="${DATA_DIR}/config/rconpw"
if [[ -z "${RCON_PASSWORD:-}" ]]; then
    if [[ -f "${RCON_PW_FILE}" ]]; then
        RCON_PASSWORD="$(cat "${RCON_PW_FILE}")"
    else
        RCON_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '/+=\n' | cut -c1-24)"
        printf '%s' "${RCON_PASSWORD}" > "${RCON_PW_FILE}"
        chmod 0600 "${RCON_PW_FILE}"
        log "Generated a random RCON password, stored in ${RCON_PW_FILE}"
    fi
fi

# --- map creation ---------------------------------------------------------
SAVE_FILE="${DATA_DIR}/saves/${SAVE_NAME:-default}.zip"
shopt -s nullglob
existing_saves=("${DATA_DIR}"/saves/*.zip)
shopt -u nullglob

if [[ ${#existing_saves[@]} -eq 0 ]]; then
    if is_true "${GENERATE_NEW_SAVE:-true}"; then
        log "No save found, creating ${SAVE_FILE}"
        create_args=(--create "${SAVE_FILE}" --config "${CONFIG_FILE}")
        [[ -f "${MAP_GEN_SETTINGS}" ]] && create_args+=(--map-gen-settings "${MAP_GEN_SETTINGS}")
        [[ -f "${MAP_SETTINGS}" ]] && create_args+=(--map-settings "${MAP_SETTINGS}")
        [[ -n "${MAP_GEN_SEED:-}" ]] && create_args+=(--map-gen-seed "${MAP_GEN_SEED}")
        [[ -n "${PRESET:-}" ]] && create_args+=(--preset "${PRESET}")
        "${BINARY}" "${create_args[@]}"
    else
        die "No save in ${DATA_DIR}/saves and GENERATE_NEW_SAVE is disabled"
    fi
fi

# --- assemble the server command -----------------------------------------
args=(--config "${CONFIG_FILE}" --mod-directory "${DATA_DIR}/mods")

if is_true "${LOAD_LATEST_SAVE:-true}"; then
    args+=(--start-server-load-latest)
else
    [[ -f "${SAVE_FILE}" ]] || die "Save ${SAVE_FILE} does not exist"
    args+=(--start-server "${SAVE_FILE}")
fi

args+=(--server-settings "${SERVER_SETTINGS}")
args+=(--port "${PORT:-34197}")
[[ -n "${BIND:-}" ]] && args+=(--bind "${BIND}")
[[ -f "${SERVER_WHITELIST}" ]] && args+=(--server-whitelist "${SERVER_WHITELIST}" --use-server-whitelist)
[[ -n "${SERVER_BANLIST:-}" ]] && args+=(--server-banlist "${SERVER_BANLIST}")
[[ -n "${SERVER_ADMINLIST:-}" ]] && args+=(--server-adminlist "${SERVER_ADMINLIST}")
[[ -n "${CONSOLE_LOG:-}" ]] && args+=(--console-log "${CONSOLE_LOG}")

if [[ -n "${RCON_PASSWORD:-}" ]]; then
    args+=(--rcon-port "${RCON_PORT:-27015}" --rcon-password "${RCON_PASSWORD}")
    [[ -n "${RCON_BIND:-}" ]] && args+=(--rcon-bind "${RCON_BIND}")
fi

# Anything passed to `docker run` is appended, and FACTORIO_ARGS lets a
# compose file add flags without overriding the command.
if [[ -n "${FACTORIO_ARGS:-}" ]]; then
    read -r -a extra_args <<< "${FACTORIO_ARGS}"
    args+=("${extra_args[@]}")
fi
args+=("$@")

log "Starting Factorio ${FACTORIO_VERSION:-unknown} headless server"
exec "${BINARY}" "${args[@]}"
